name = "elevatorbud-landing"
compatibility_date = "2025-04-01"
compatibility_flags = ["nodejs_compat"]
main = "@tanstack/react-start/server-entry"

routes = [
  { pattern = "hisskompetens.se", custom_domain = true },
  { pattern = "www.hisskompetens.se", custom_domain = true },
]
